### ISSUE TITLE
Login to ATmosphere

### ISSUE THREAD

**Issue by bmann** [ATProtoApps/community#3]
To prevent “login with Bluesky” becoming the default call to action, we’re going to need an alternative. 

“Login to ATmosphere” is one suggestion. 

Needs some work on naming, and definitely needs a couple of different design treatments.

**Comment by nekorug** [comment]
ATmosphere is a fun but silly developer nickname. It really should not be used in branding or as a name.

When you login to atproto you use your handle, your AT-handle, so my suggestion is:

> `Login with your @handle`

**Comment by tom-sherman** [comment]
Some previous discussion on login flow terminology in the oauth roadmap discussion thread

https://github.com/bluesky-social/atproto/discussions/2656#discussioncomment-10164044

https://github.com/bluesky-social/atproto/discussions/2656#discussioncomment-10663063

**Comment by tomcreighton** [comment]
Idea: mark that evokes the @ symbol, nods to the universality of a distributed identity (wildcard *!), can be used with other words/concepts, easy to drop in as a glyph in different situations. (Very much just thinking/sketching aloud here, approaching this from a design perspective rather than a technical one.)

![atproto](https://github.com/user-attachments/assets/d7dcec9b-1b11-4d21-8076-5706b0e1890e)

**Comment by tomcreighton** [comment]
@bmann Just following up from your Bluesky thread. ^ while this is just a riff, I feel like there’s some further useful exploration to do here.

**Comment by bmann** [comment]
Thanks @tomcreighton this is interesting — my GH notifications process continues to be terrible, my apologies! 

Maybe interesting to have a live chat about this? I’ll ping you!

**Comment by bmann** [comment]
Thanks everyone for your time on the call today. I really should do these sorts of things as discussions, so meet me over there https://github.com/orgs/ATProtoApps/discussions/12
